# Generated by Django 6.0.3 on 2026-03-14 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('HACKATHON', 'Hackathon'), ('INTERNSHIP', 'Internship'), ('RESEARCH', 'Research Publication'), ('TECH_COMP', 'Technical Competition'), ('SPORTS', 'Sports Achievement'), ('CULTURAL', 'Cultural Activity'), ('WORKSHOP', 'Workshop/Seminar'), ('OTHER', 'Other Achievement')], max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('organizing_body', models.CharField(max_length=200)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='achievements/certificates/')),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='achievements/proofs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='students.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
