# Generated by Django 6.0.3 on 2026-03-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_temporaryregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationrequest',
            options={'managed': False},
        ),
    ]
